name: Test, Build, and Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run Jest tests
      - name: Run tests
        run: npm test

      # 5️⃣ Deploy to EC2 via SSH
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Responsive_Navbar || git clone "https://github.com/BkBharani/Responsive_Navbar.git"
            cd ~/Responsive_Navbar
            git pull
            docker stop navbar || true
            docker rm navbar || true
            docker build -t navbar .
            docker run -d -p 80:80 --name navbar navbar
