name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Responsive_Navbar || git clone "https://github.com/BkBharani/Responsive_Navbar.git"
            cd ~/Responsive_Navbar
            git pull
            docker stop navbar || true
            docker rm navbar || true
            docker build -t navbar .
            docker run -d -p 80:80 --name navbar navbar
